// Generates supabase/seed.sql from the same Casa do Mar data the demo mode uses,
// so both data sources always show the identical restaurant.
// Run: node scripts/gen-seed.ts
import { writeFileSync } from 'node:fs'
import { casaDoMar, categories, dishes, tables } from '../src/data/seed/casaDoMar.ts'

class Json {
  value: unknown
  constructor(value: unknown) {
    this.value = value
  }
}
const q = (v: unknown): string => {
  if (v === undefined || v === null) return 'null'
  if (v instanceof Json) return `${q(JSON.stringify(v.value))}::jsonb`
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v) && v.every((x) => typeof x === 'string')) return `array[${v.map(q).join(', ')}]::text[]`
  if (typeof v === 'object') return `${q(JSON.stringify(v))}::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}
const row = (vals: unknown[]) => `  (${vals.map(q).join(', ')})`

const r = casaDoMar
const sql = `-- Generated by scripts/gen-seed.ts — do not edit by hand.
-- Casa do Mar demo tenant. After seeding, make yourself the owner:
--   insert into restaurant_members (restaurant_id, user_id, role)
--   values ('${r.id}', '<your auth.users id>', 'owner');

insert into organizations (id, name) values ('${r.id}', ${q(r.name)}) on conflict do nothing;

insert into restaurants (id, organization_id, slug, name, tagline, description, cuisine, address, city, phone, locale, currency, timezone, brand, settings, plan, is_published)
values
${row([r.id, r.id, r.slug, r.name, r.tagline, r.description, r.cuisine, r.address, r.city, r.phone, r.locale, r.currency, r.timezone, r.brand, r.settings, r.plan, r.isPublished])}
on conflict (id) do nothing;

insert into restaurant_counters (restaurant_id) values ('${r.id}') on conflict do nothing;

insert into menu_categories (id, restaurant_id, name, description, position, is_visible) values
${categories.map((c) => row([c.id, c.restaurantId, c.name, c.description, c.position, c.isVisible])).join(',\n')}
on conflict (id) do nothing;

insert into dishes (id, restaurant_id, category_id, name, description, price_cents, image_url, allergens, ingredients, tags, options, pairing, prep_minutes, is_available, is_featured, position) values
${dishes
  .map((d) => row([d.id, d.restaurantId, d.categoryId, d.name, d.description, d.priceCents, d.imageUrl, d.allergens, d.ingredients, d.tags, new Json(d.options), d.pairing, d.prepMinutes, d.isAvailable, d.isFeatured, d.position]))
  .join(',\n')}
on conflict (id) do nothing;

insert into restaurant_tables (id, restaurant_id, label, area, seats, qr_token, is_active, position) values
${tables.map((t) => row([t.id, t.restaurantId, t.label, t.area, t.seats, t.qrToken, t.isActive, t.position])).join(',\n')}
on conflict (id) do nothing;
`
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log('supabase/seed.sql written')
